name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Steps to validate application build
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Echo
        run: |
          echo Build process

  deployment:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch .env
          echo PLANET_SOURCE_DB_HOST=${{ vars.PLANET_SOURCE_DB_HOST }} >> .env
          echo PLANET_SOURCE_DB_USER=${{ vars.PLANET_SOURCE_DB_USER }} >> .env
          echo PLANET_SOURCE_DB_PASSWORD=${{ secrets.PLANET_SOURCE_DB_PASSWORD }} >> .env
          echo PLANET_SOURCE_DB_NAME=${{ vars.PLANET_SOURCE_DB_NAME }} >> .env
          cat .env

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: '${{ vars.DOCKER_HUB_USER }}'
          password: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tgkirupakaran/kurunagai-admin-api
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

