name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push to DockerHub
      uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
        # Docker Registry Url, eg: docker.io
        registry_url: 
        # Docker Image Repository Name, eg: username/demo-app
        repository_name: 
        # Docker Login UserName, from: https://hub.docker.com/
        user_name: 
        # Docker Login Access Token, from: https://hub.docker.com/
        password: 
        # Image Build Version
        image_version: 
        # Docker File Directory, Default Current Directory (.)
        docker_file: # optional, default is .
